Hw 10 tiurin artur
tyurinart14/Eshop pull request #12
Opened 2022-09-01 16:02 UTC by tyurinart14

2022-10-17 09:35 UTC, shorodilov requested changes
Треба полагодити міграції проекта

2022-10-28 15:06 UTC, tyurinart14 commented
.idea  удалил

2022-10-28 15:40 UTC, shorodilov requested changes
Треба полагодити модель та URLСonf для товарів

2022-10-28 15:48 UTC, shorodilov approved these changes
Фільтр краще прибрати, або переробити.

2022-10-28 15:48 UTC, shorodilov commented on products/urls.py
>      path('product/<int:num>/<slug:slug>/', views.product_detail, name="product"),
Оцей slug у моделі не використовується. По факту його можна прибрати.

2022-11-02 13:25 UTC, merged