Moved all styles to separate html.
tyurinart14/Eshop pull request #4
Opened 2022-08-03 16:23 UTC by tyurinart14

Moved all styles to separate html and delete unnecessary template (basket.html)

2022-08-03 17:53 UTC, shorodilov requested changes
Додай 'manage.py`

2022-08-03 17:53 UTC, shorodilov commented on templates/homepage.html
> +        <form action="http://127.0.0.1:8000/basket?" target="_self">
Не роби так. `action="/basket"`

2022-08-03 17:54 UTC, shorodilov approved these changes

2022-08-03 21:25 UTC, shorodilov submitted a review, later dismissed

2022-08-05 10:56 UTC, shorodilov requested changes
Треба зробити виправленя до темплейтів та перенести до їх до відповідного застосунку.

2022-08-05 10:56 UTC, shorodilov commented on templates/homepage.html
> +    </figure>
Треба переробити з використанням цикла

2022-08-05 10:58 UTC, shorodilov commented
Треба зробити звʼязок між моделями 1-n

2022-08-06 10:51 UTC, shorodilov requested changes
Дивись коментарі до PR

2022-08-06 10:51 UTC, shorodilov commented on djangoEshop/view.py
> +]}
А навіщо ти створив два словники?

2022-08-06 10:51 UTC, shorodilov commented on templates/homepage.html
> +            <div style="text-align: center;"><a href="{{ elem.address }}">{{ elem.name }}</a></div>
Посилання краще все ж робити через тег DTL `{% url ... %}`

2022-08-06 10:51 UTC, shorodilov commented on aplication/models.py
> +    cat = models.ForeignKey('Category', on_delete=models.PROTECT, null=True)
Зміни у моделі бачу. Але без міграцій БД проекта про них не дізнається.

2022-08-06 10:51 UTC, shorodilov commented on djangoEshop/view.py
>  def client_page(request: HttpRequest, id: str) -> render:
Ти обманюєш своїх колег. `render` - це функція, твій вью повертає `HttpResponse` (власно, вью повинен або повертати відгук, або підіймати виключення).

2022-08-06 10:51 UTC, shorodilov commented on djangoEshop/view.py
>  def homepage(request: HttpRequest) -> render:
Ти обманюєш своїх колег. render - це функція, твій вью повертає HttpResponse (власно, вью повинен або повертати відгук, або підіймати виключення).

2022-08-06 10:59 UTC, tyurinart14 commented on djangoEshop/view.py
> +]}
у них із спільної інформації лише "name", а все інше - різне

2022-08-06 12:36 UTC, shorodilov commented on djangoEshop/view.py
> +]}
Ок, що таке макбук з першого та що таке макбук з другого?

2022-08-06 12:58 UTC, tyurinart14 commented on djangoEshop/view.py
> +]}
це "name" ....  тобто мені поєднати 2 словника ? просто в мене була така логіка - на одну сторінку - один словник, думав так буде зручніше вносити зміни (якщо потрібно буде)

2022-08-06 13:09 UTC, shorodilov commented on djangoEshop/view.py
> +]}
Я б поєднав, бо це одні й ті самі об'єкти по 2-х словниках

2022-08-07 18:25 UTC, shorodilov approved these changes
Треба зробити рефакторінг вью функцій.

2022-08-07 18:25 UTC, shorodilov commented on djangoEshop/view.py
> +def client_page(request: HttpRequest, id: str):
```suggestion
def client_page(request: HttpRequest, id: str):
    for name in context_info:
        if name["id"] == id:
            return render(request, 'client_page.html', name)
    raise Http404()
```

2022-08-07 18:25 UTC, shorodilov commented on djangoEshop/view.py
> +def product_all(request: HttpRequest, item_name: str):
```suggestion
def product_all(request: HttpRequest, item_name: str):
    for name in context_product['products']:
        if name["slug"] == item_name:
            return render(request, 'product_all.html', name)
    raise Http404()
```

2022-08-11 18:26 UTC, closed without merging